<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Index - QuickStart Bootstrap Template</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Main CSS File -->
   
  <link rel="stylesheet" href="assets/css/main.css">


  <!-- =======================================================
  * Template Name: QuickStart
  * Template URL: https://bootstrapmade.com/quickstart-bootstrap-startup-website-template/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

      <a href="index.html" class="logo d-flex align-items-center me-auto">
        <img src="assets/img/logo.png" alt="">
        <h1 class="sitename">NotreBibliotheque</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="index.html" class="active">Acceuil</a></li>
          <li><a href="index.html#services">Livres</a></li>
          <!-- <li><a href="index.html#features">Features</a></li>
          <li><a href="index.html#services">Services</a></li>
          <li><a href="index.html#pricing">Pricing</a></li> -->
          <li class="dropdown"><a href="#"><span>Themes</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li><a href="#"></a></li>
              <li class="dropdown"><a href="#"><span>Livres scolaire</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                <ul>
                  <li><a href="#">Histoire</a></li>
                  <li><a href="#">Mathématique</a></li>
                  <li><a href="#">Science</a></li>
                  <li><a href="#">Informatique</a></li>
                  <li><a href="#">Langues</a></li>
                </ul>
              </li>
              <li><a href="#">Policier</a></li>
              <li><a href="#">Aventure</a></li>
              <li><a href="#">Science-Fiction</a></li>
              <li><a href="#">Fantasy</a></li>
            </ul>
          </li>
          <li><a href="index.html#contact" style="margin-right:50px ;">contactez-nous</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

      <form class="form-inline" >
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          
      </form>

      <a class="btn-getstarted" href="sign.php">s'inscrire</a>

    </div>
  </header>


  <!--HERO SECTION-->
  <main class="main">

    <section id="hero" class="hero section">
      <div class="hero-bg">
        <img src="assets/img/hero-bg-light.webp" alt="">
      </div>
      <div class="container text-center">
        <div class="d-flex flex-column justify-content-center align-items-center">
          <h1 data-aos="fade-up">S'inscrire</h1>
          <div>
                <fieldset >
                    <form name="form1" method="post" action="" class="fil">
                        <div class="mb-3">
                          <input type="text" class="form-control" name="nom"  placeholder="Nom" required>
                        </div>
                        <div class="mb-3">
                          <input type="text" class="form-control" name="prenom"  placeholder="Prénom" required>
                        </div>
                        <div class="mb-3">
                          <input type="text" class="form-control" name="username"  placeholder="username" required>
                        </div>
                        <div class="mb-3">
                          <input type="email" class="form-control" name="mail" aria-describedby="emailHelp" placeholder="Email" required>
                        </div>
                        <div class="mb-3">
                          <input type="tel" class="form-control" name="telephone" placeholder="Num Telephone" required>
                        </div>
                        <div class="mb-3">
                          <input type="tel" class="form-control" name="enrollment" placeholder="num inscription" required>
                        </div>
                        <div class="mb-3">
                          <input type="tel" class="form-control" name="sem" placeholder="sem" required>
                        </div>
                        <div class="mb-3">
                          <input type="password" class="form-control" name="psw" placeholder="Mot de passe" required>
                        </div>
                        <input type="submit" class="btn btn-primary" name="submit1" value=Submit >
                      </form>

                  </fieldset>
          </div>
        </div>
      </div>

    </section>
    
  </main>

